-- DDL

CREATE TABLE CATEGORY
(
    ID       INTEGER PRIMARY KEY,
    NAME     VARCHAR(25)
);


CREATE TABLE BOOK
(
    ID         INTEGER PRIMARY KEY,
    TITLE      VARCHAR(30),
    AUTHOR     VARCHAR(50),
    PUBLISHER  VARCHAR(30),
    YEARISSUE  INTEGER,
    CATEGORY   INTEGER,
    CONSTRAINT FK_CATEGORYNO FOREIGN KEY (CATEGORY) REFERENCES CATEGORY (ID)
);

COMMIT;