-- DML

INSERT INTO CATEGORY VALUES (10, 'Энциклопедии');
INSERT INTO CATEGORY VALUES (20, 'Естественные науки');
INSERT INTO CATEGORY VALUES (30, 'Техника. Технические науки');
INSERT INTO CATEGORY VALUES (40, 'Сельское и лесное хозяйство');
INSERT INTO CATEGORY VALUES (50, 'Здравоохранение. Медицинские науки');
INSERT INTO CATEGORY VALUES (60, 'Социальные и гуманитарные науки');
INSERT INTO CATEGORY VALUES (70, 'Культура. Наука. Просвещение');
INSERT INTO CATEGORY VALUES (80, 'Филологические науки. Художественная литература');
INSERT INTO CATEGORY VALUES (90, 'Литература универсального содержания');

INSERT INTO BOOK VALUES (7839, 'JOHN', 'KING', 1985, 200, 10);
INSERT INTO BOOK VALUES (7698, 'MERRY', 'BLAKE', 2000, 600, 10);
INSERT INTO BOOK VALUES (7782, 'JOHN', 'CLARK', 1999, 320, 20);
INSERT INTO BOOK VALUES (7566, 'JOE', 'JONES', 1986, 156, 20);
INSERT INTO BOOK VALUES (7788, 'JOHN', 'SCOTT', 2001, 100, 30);
INSERT INTO BOOK VALUES (7902, 'JOHN', 'FORD', 1995, 160, 30);

INSERT INTO AUTHOR VALUES (1, 'IVAN', 'IVANOV');
INSERT INTO AUTHOR VALUES (2, 'PETR', 'PETROV');
INSERT INTO AUTHOR VALUES (3, 'SEMEN', 'SEMENOV');
INSERT INTO AUTHOR VALUES (4, 'SERGEY', 'SERGEEV');

INSERT INTO BOOK_AUTHOR VALUES (7839, 1);
INSERT INTO BOOK_AUTHOR VALUES (7839, 2);
INSERT INTO BOOK_AUTHOR VALUES (7566, 3);
INSERT INTO BOOK_AUTHOR VALUES (7788, 4);
INSERT INTO BOOK_AUTHOR VALUES (7698, 4);
INSERT INTO BOOK_AUTHOR VALUES (7698, 3);
